In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
zoo=pd.read_csv('zoo (1).csv')
zoo

animal  uniq_id  water_need
0   elephant     1001         500
1   elephant     1002         600
2   elephant     1003         550
3      tiger     1004         300
4      tiger     1005         320
5      tiger     1006         330
6      tiger     1007         290
7      tiger     1008         310
8      zebra     1009         200
9      zebra     1010         220
10     zebra     1011         240
11     zebra     1012         230
12     zebra     1013         220
13     zebra     1014         100
14     zebra     1015          80
15      lion     1016         420
16      lion     1017         600
17      lion     1018         500
18      lion     1019         390
19  kangaroo     1020         410
20  kangaroo     1021         430
21  kangaroo     1022         410

In [3]:
zoo.groupby('animal').mean()['water_need']

animal
elephant    550.000000
kangaroo    416.666667
lion        477.500000
tiger       310.000000
zebra       184.285714
Name: water_need, dtype: float64

In [4]:
a=input("My name:")
print(a)


My name:nikhil
nikhil


In [5]:
 b=input("Input your name: ") 

Input your name: 


In [6]:
 a = float(raw_input('Type a number: ')) 

NameError: name 'raw_input' is not defined

In [7]:
import numpy as np


In [8]:
data = np.zeros((5,2), dtype='float') # Make an empty 2-d array 
data[:,0] = np.arange(5.0) # Fill one column with numbers 
data[:,1] = data[:,0] ** 2.0 

In [9]:
data

array([[ 0.,  0.],
       [ 1.,  1.],
       [ 2.,  4.],
       [ 3.,  9.],
       [ 4., 16.]])

In [10]:
d1=np.zeros((10,3),dtype='int')

In [11]:
d1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [12]:
n=[1,2,3,4,5,6,7,8,9]

In [13]:
for i in n:
    n*2
    
    

In [14]:
d1[:,0]=np.arange(3,33,3)

In [15]:
d1

array([[ 3,  0,  0],
       [ 6,  0,  0],
       [ 9,  0,  0],
       [12,  0,  0],
       [15,  0,  0],
       [18,  0,  0],
       [21,  0,  0],
       [24,  0,  0],
       [27,  0,  0],
       [30,  0,  0]])

In [16]:
d1[:,1]=np.arange(4,44,4)

In [17]:
d1

array([[ 3,  4,  0],
       [ 6,  8,  0],
       [ 9, 12,  0],
       [12, 16,  0],
       [15, 20,  0],
       [18, 24,  0],
       [21, 28,  0],
       [24, 32,  0],
       [27, 36,  0],
       [30, 40,  0]])

In [18]:
d1[:,2]=np.arange(5,55,5)

In [19]:
d1

array([[ 3,  4,  5],
       [ 6,  8, 10],
       [ 9, 12, 15],
       [12, 16, 20],
       [15, 20, 25],
       [18, 24, 30],
       [21, 28, 35],
       [24, 32, 40],
       [27, 36, 45],
       [30, 40, 50]])

In [20]:
d2=np.zeros((10,3),dtype='int')
d2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [21]:
d2[:,0]=np.arange(2,22,2)

In [22]:
d2

array([[ 2,  0,  0],
       [ 4,  0,  0],
       [ 6,  0,  0],
       [ 8,  0,  0],
       [10,  0,  0],
       [12,  0,  0],
       [14,  0,  0],
       [16,  0,  0],
       [18,  0,  0],
       [20,  0,  0]])

In [23]:
n=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

In [24]:
n

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [25]:
a=np.array([n])

answer = (a[a%2==1])
print (answer)   

[ 1  3  5  7  9 11 13 15 17 19]


In [26]:
d2[:,1]=answer

In [27]:
d2

array([[ 2,  1,  0],
       [ 4,  3,  0],
       [ 6,  5,  0],
       [ 8,  7,  0],
       [10,  9,  0],
       [12, 11,  0],
       [14, 13,  0],
       [16, 15,  0],
       [18, 17,  0],
       [20, 19,  0]])

In [28]:
lower=2
upper=30
prime=[]

for num in range(lower,upper):
    isprime=True
    for i in range(2,num):
        if (num % i) == 0:
            isprime=False
            
            
    if isprime:
        prime.append(num)
                
              

In [29]:
d2[:,2]=prime

In [30]:
d2

array([[ 2,  1,  2],
       [ 4,  3,  3],
       [ 6,  5,  5],
       [ 8,  7,  7],
       [10,  9, 11],
       [12, 11, 13],
       [14, 13, 17],
       [16, 15, 19],
       [18, 17, 23],
       [20, 19, 29]])

In [31]:
lower = 2
upper = 29
prime2=[]



for num in range(lower,upper + 1):

   if num > 1:
       for i in range(2,num):
           if (num % i) == 0:
               break
       else:
        prime2.append(num)
           

In [32]:
prime2

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

In [33]:
d2[:,2]=prime2

In [34]:
d2

array([[ 2,  1,  2],
       [ 4,  3,  3],
       [ 6,  5,  5],
       [ 8,  7,  7],
       [10,  9, 11],
       [12, 11, 13],
       [14, 13, 17],
       [16, 15, 19],
       [18, 17, 23],
       [20, 19, 29]])

In [35]:
#saving an array to file 
np.savetxt('zoo.txt',d2,fmt='%.3f')

In [36]:
#load an array to file
d2=np.loadtxt('zoo.txt')

# print(d2)

In [37]:
print(d2)

[[ 2.  1.  2.]
 [ 4.  3.  3.]
 [ 6.  5.  5.]
 [ 8.  7.  7.]
 [10.  9. 11.]
 [12. 11. 13.]
 [14. 13. 17.]
 [16. 15. 19.]
 [18. 17. 23.]
 [20. 19. 29.]]


In [38]:
x=float(input("number:"))
y=x**2-1

y

number:


ValueError: could not convert string to float: 

In [39]:
x1=float(input('number x:'))
y1=float(input('number y:'))
z=x1**2+y1**2
z


number x:


ValueError: could not convert string to float: 

In [40]:
a=float(input('number a:'))
b=float(input('number b:'))
c=float(input('number c'))
x=float(input('number x: '))
y=a*x**2+b*x+c
y

number a:


ValueError: could not convert string to float: 

In [41]:
a=[3,54,26,90]
a


[3, 54, 26, 90]

In [42]:
b=[3,54,'llama',a]
b


[3, 54, 'llama', [3, 54, 26, 90]]

In [43]:
a=[3,54,26,90] 
b=[3,54,'llama',a]

In [44]:
b

[3, 54, 'llama', [3, 54, 26, 90]]

In [45]:
a[0]

3

In [45]:
a[3]

90

In [46]:
a[-1]

90

In [47]:
b[2]

'llama'

In [48]:

b[3][2]

26

In [49]:
a=[12,23,34,45,56,67,78] 
a[3:6] 


[45, 56, 67]

In [50]:
a[3:]

[45, 56, 67, 78]

In [51]:
a=[1,2,3] 
b=[4,5,6] 
c=a+b 
c

[1, 2, 3, 4, 5, 6]

In [52]:
a=[1,2,3,4,5,6,7,8,9] 
a.insert(3,99) 
a

[1, 2, 3, 99, 4, 5, 6, 7, 8, 9]

In [53]:
a=[1,2,3] 
b=[4,5,6] 
c = zip(a,b)
print(c)

In [54]:
a=[1.0,2.0,3.0] 
b=map(int,a)
b

In [55]:
a=(1,2,3)
a


(1, 2, 3)

In [56]:
type(a)

tuple

In [57]:
a[1]

2

In [58]:
a='This parrot is dead'
a    

'This parrot is dead'

In [59]:
a[5:11]

'parrot'

In [62]:
a.find('This')

0

In [63]:
a=np.arange(9, dtype='float')

In [64]:
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [67]:
a=np.arange(9.0) 
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [69]:
a.shape=(3,3)
a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [70]:
b=a**2
b


array([[ 0.,  1.,  4.],
       [ 9., 16., 25.],
       [36., 49., 64.]])

In [73]:
a=np.arange(9, dtype='float')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [74]:
a[1:5]

array([1., 2., 3., 4.])

In [80]:
b=np.arange(9,dtype='float')
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [81]:
a.shape=(3,3)
a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [82]:
a[2,1]

7.0

In [90]:
#dictionary
phonebook={}
phonebook['fried']='12345'
phonebook['claire']='0234 7432'
phonebook

{'fried': '12345', 'claire': '0234 7432'}

In [84]:
phonebook['claire']

'0234 7432'

In [91]:
phonebook['fried']

'12345'

In [92]:
len(phonebook)

2

In [2]:
x1={'nikhil':21,'rakesh':32,'ash':42,'eng':23,'frace':32,'mam':44,'sir':45,'will':1991,'pep':32,'ink':56}
x2=[21,32,42,23,22,44,45,1991,44,53]

In [3]:
x1['will']

1991

In [4]:
x1['frace']

32

In [5]:
x1['cola']

KeyError: 'cola'

In [1]:
x1=['nikhil','ram','will']
x2=[21,32,1991]
name=input('enter your frends name:')
print('you have',len(names),"freands")
index=names.index(name)
print(name,'is number',index,'in your list')
print(name,'was born in ',y)

enter your frends name:ram


NameError: name 'names' is not defined

In [7]:
x

In [8]:
import numpy as np

In [22]:
b=np.arange(100,dtype='float')
b

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [23]:
b

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [24]:
m.shape(3,3)

TypeError: 'tuple' object is not callable

In [47]:
x1=['nikhil','ram','will']
x2=[21,32,1991]
name=input('enter your friends name:')
print('you have',len(x1),"friends")
index=x1.index(name)
print(name,'is number',index,'in your list')
print(name,'was born in ',x2[index])

enter your friends name:nikhil
you have 3 friends
nikhil is number 0 in your list
nikhil was born in  21


In [13]:
fruits=['banana','apple','orange','mango','pineapple','grapes','sapota','watermelon','strawberry','blueberry','kiwi','jackfruit']
shop=['ram',2,3,4,'nikhil',6,7,8,9,10,11,12]
price=[10,30,40,50,60,30,40,60,54,32,43,21]
location=['hyderabad']
pick=input('enter fruit name: ')
index1=fruits.index(pick)
index2=shop[index1]
index3=price[index1]
index4=location[0]
print('you have',pick,'in',index2,'shop')
print(pick,'the price is',index3)
print(pick,'is in location',index4)

enter fruit name: blueberry
you have blueberry in 10 shop
blueberry the price is 32
blueberry is in location hyderabad


In [17]:
import random 
fruits=['banana','apple','orange','mango','pineapple','grapes','sapota','watermelon','strawberry','blueberry','kiwi','jackfruit']
shop=random.randint(1, 12) 
price=random.randint(40, 52)
location=['hyderabad']
pick=input('enter fruit name: ')
index1=fruits.index(pick)
index4=location[0]
print('you have',pick,'in number',shop,'shop')
print(pick,'the price is',price)
print(pick,'is in location',index4)

enter fruit name: sapota
you have sapota in number 11 shop
sapota the price is 48
sapota is in location hyderabad


In [25]:
import random 
import string
def randomString(stringLength=10):
    
    letters = string.ascii_lowercase
    return ''.join(random.choice(letters) for i in range(stringLength))

fruits=['banana','apple','orange','mango','pineapple','grapes','sapota','watermelon','strawberry','blueberry','kiwi','jackfruit']
shop=random.randint(1, 12) 
price=random.randint(40, 52)

pick=input('enter fruit name: ')
index1=fruits.index(pick)

print('you have',pick,'in number',shop,'shop')
print(pick,'the price is',price)
print(pick,'is in location',randomString())

enter fruit name: banana
you have banana in number 10 shop
banana the price is 42
banana is in location lbjjmbwapottsqaphavy
